radio.onReceivedNumber(function (receivedNumber) {
    if (receivedNumber == 4) {
        radio.sendNumber(2)
        basic.showIcon(IconNames.Butterfly)
        strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
        strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Red))
        strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Red))
        strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Red))
        strip.setPixelColor(4, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(5, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(6, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(7, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(8, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(9, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(10, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(11, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(12, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(13, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(14, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(15, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(16, neopixel.colors(NeoPixelColors.Red))
        strip.setPixelColor(17, neopixel.colors(NeoPixelColors.Red))
        strip.setPixelColor(18, neopixel.colors(NeoPixelColors.Red))
        strip.setPixelColor(19, neopixel.colors(NeoPixelColors.Red))
        strip.show()
    }
    if (receivedNumber == 3) {
        radio.sendNumber(1)
        basic.showIcon(IconNames.StickFigure)
        strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
        strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Red))
        strip.setPixelColor(4, neopixel.colors(NeoPixelColors.Red))
        strip.setPixelColor(5, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(6, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(7, neopixel.colors(NeoPixelColors.Red))
        strip.setPixelColor(8, neopixel.colors(NeoPixelColors.Red))
        strip.setPixelColor(9, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(10, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(11, neopixel.colors(NeoPixelColors.Red))
        strip.setPixelColor(12, neopixel.colors(NeoPixelColors.Red))
        strip.setPixelColor(13, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(14, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(15, neopixel.colors(NeoPixelColors.Red))
        strip.setPixelColor(16, neopixel.colors(NeoPixelColors.Red))
        strip.setPixelColor(17, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(18, neopixel.colors(NeoPixelColors.Green))
        strip.setPixelColor(19, neopixel.colors(NeoPixelColors.Red))
        strip.show()
    }
})
input.onButtonPressed(Button.A, function () {
    radio.sendNumber(1)
    basic.showIcon(IconNames.StickFigure)
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(4, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(5, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(6, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(7, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(8, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(9, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(10, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(11, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(12, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(13, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(14, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(15, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(16, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(17, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(18, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(19, neopixel.colors(NeoPixelColors.Red))
    strip.show()
})
input.onButtonPressed(Button.B, function () {
    radio.sendNumber(2)
    basic.showIcon(IconNames.Butterfly)
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(4, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(5, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(6, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(7, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(8, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(9, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(10, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(11, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(12, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(13, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(14, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(15, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(16, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(17, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(18, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(19, neopixel.colors(NeoPixelColors.Red))
    strip.show()
})
input.onLogoEvent(TouchButtonEvent.Pressed, function () {
    strip.showColor(neopixel.colors(NeoPixelColors.White))
})
let strip: neopixel.Strip = null
strip = neopixel.create(DigitalPin.P8, 20, NeoPixelMode.RGB)
radio.setGroup(58)
strip.showColor(neopixel.colors(NeoPixelColors.Black))
